#------------------------------------------------------------------------------#
# Site settings

title: Stop The Spies
email: admin@stopthespies.org
description: Stop The Spies is an Australian campaign to raise awareness about new data retention laws.
baseurl: ""
github_username:  stopthespies

# :TODO: point to live site after validating social tags
url: http://stage.stopthespies.org
domain: stage.stopthespies.org


#------------------------------------------------------------------------------#
# social metadata

twitter_username: stopthespies
facebook_username: stopthespiesaustralia
# facebook_admin_userid :
# facebook_app_id :

# :TODO: - final image paths should be relative URLs via `| prepend: site.baseurl`
#share_twitter_card: summary_large_image
share_image_twitter: http://dummyimage.com/280x150/049/fff		# Prior to approval for large image cards, use the smaller image size
#share_image_twitter: http://dummyimage.com/450x250/049/fff		# Once approved, switch to the bigger ones
share_image_facebook: http://dummyimage.com/1200x1200/009/fff
share_image_gplus: http://dummyimage.com/800x600/900/fff


#------------------------------------------------------------------------------#
# Build settings
markdown: kramdown
permalink: pretty

sass:
    sass_dir: css/_sass
